services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5433:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:19
    command: --config /workspace/odoo.conf -u estate
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - odoo-extra-addons:/mnt/extra-addons
      - .:/workspace
    restart: unless-stopped

volumes:
  odoo-db-data:
  odoo-web-data:
  odoo-extra-addons:

    # vhdh-vde7-srnd
