[options]
admin_passwd = $pbkdf2-sha512$600000$JsRYC2FszXkPIeR8b62VMg$Wi9bcVf8E/9JrqWnar.zMQvPUNhO47xIZjdKw75HHY38MafFD4d9oBbusk7FQxwq2Jk55O/BYmGkThxxNPAs7A
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /workspace/tutorials